### ISSUE TITLE
Package doesn't work without template compiler?

### ISSUE THREAD

**Issue by Herteby** [michaelfitzhavey/vue-json-tree-view#10]
First I tried this:
```
import TreeView from "vue-json-tree-view"
Vue.use(TreeView)
```
Which gave the error "You are using the runtime-only build of Vue where the template compiler is not available..."
So I tried this instead:
```
import TreeView from "vue-json-tree-view/dist/vue-json-tree-view.min.js"
Vue.use(TreeView)
```
But I still get the same error.

**Comment by colwilson** [comment]
I get the same.

**Comment by arvidkahl** [comment]
This probably originates from the build chain. If someone is willing to work on a runtime-only build of the library, a pull request would be greatly appreciated.

**Comment by syuilo** [comment]
I still get the same error.

**Comment by rvyas** [comment]
Same here. Getting this warning:
> [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by rvyas** [comment]
Same as #23

**Comment by morrislaptop** [comment]
I used `import TreeView from 'vue-json-tree-view/src/TreeView'` instead and then

```
components: {
    TreeView
  }
```

**Comment by bradstewart** [comment]
The issue stems from: https://github.com/arvidkahl/vue-json-tree-view/commit/67abaa155969a198e869b9665756e3a9c7830bef#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

That commit removed vue-loader>10 and vue-template-compiler, which are required for runtime-only builds.
