### ISSUE TITLE
Q: Any ideas on custom templates?

### ISSUE THREAD

**Issue by nwpappas** [michaelfitzhavey/vue-json-tree-view#13]
I am trying to build a Tree component as well. This has come in very handy as reference!

But I'd like to support custom TreeViewItem templates (i.e., get a `slot` in there). Any ideas on how to take a template defined in the `TreeView` component and pass it into the child `TreeViewItem`?

**Comment by arvidkahl** [comment]
https://alligator.io/vuejs/scoped-component-slots/ has a pretty decent tutorial on that, but I have not yet worked with slots that much. But if you find a cool way, do drop me a note, I might incorporate that into this library.

**Comment by michaelfitzhavey** [comment]
Closed as not being worked on, I'm interested to look into this in the future.
