### ISSUE TITLE
Hello, JSON data is not highlighted

### ISSUE THREAD

**Issue by Ya-hui** [michaelfitzhavey/vue-json-tree-view#18]
Hello, JSON data is not highlighted

**Comment by nichtich** [comment]
You can at least configure CSS classes `tree-view-item-value` and `tree-view-item-key` but values (string, number, boolean...) get same layout. Additional styling seems to require an extension to set CSS classes based on data types in `TreeViewItemValue.vue`. I suppose pull requests are welcome.

**Comment by ad34** [comment]
hello, for some reason I have all elements rendered as white, I wonder why this is happenning. I checked for css file to link but cannot find any in vue-json-tree-view folder.

**Comment by ad34** [comment]
still have this issue. it s very strange because if I edit the element from chrome dev tools an add manually a color (for exemple), it is applied but not if I edit the classes directly (ex : tree-view-item-key)

**Comment by michaelfitzhavey** [comment]
Could you show an example of the the css you're using to style the items?

It's important to prefix the classes with a `.` (`.tree-view-item-key`) for styles to have an effect
