### ISSUE TITLE
Looking for project maintainer

### ISSUE THREAD

**Issue by arvidkahl** [michaelfitzhavey/vue-json-tree-view#25]
If anyone wants to take over maintenance of the project, please reach out.

**Comment by michaelfitzhavey** [comment]
@arvidkahl I'd be interested. This component has come in handy for me a fair few times.

**Comment by arvidkahl** [comment]
Wonderful. I've given you collaborator for now. I will transfer ownership of the repo whenever you're ready.

**Comment by michaelfitzhavey** [comment]
Ready 😄

**Comment by michaelfitzhavey** [comment]
@arvidkahl I seem to be having issues publishing updates to this repo on npm.

<img width="957" alt="screen shot 2018-08-28 at 16 53 12" src="https://user-images.githubusercontent.com/2746248/44734885-e1a7c700-aae2-11e8-8ae0-98e6e01fd702.png">

Could you give me publish rights? Thanks!

**Comment by arvidkahl** [comment]
Done. Let me know if it doesn't work please :)

**Comment by tylerkrupicka** [comment]
I created a component inspired by this one at https://github.com/tylerkrupicka/vue-json-component

I tried to do it without any dependencies to reduce bundle size, add typescript support, and increase performance.

If you guys need any help on this one down the road let me know.
