### ISSUE TITLE
Can you add color to the label

### ISSUE THREAD

**Issue by solxnp** [michaelfitzhavey/vue-json-tree-view#26]
![image](https://user-images.githubusercontent.com/18416053/39394041-5e1d52e4-4aff-11e8-9342-cbb311d4b0af.png)

**Comment by absolutehype** [comment]
`.tree-view-item-key {
    color: red;
}`

**Comment by michaelfitzhavey** [comment]
@solxnp the solution given by @absolutehype is the best way to style labels currently. The readme has been updated, feel free to open another issue if you have any problems!
