### ISSUE TITLE
Typescript Support - Missing @types

### ISSUE THREAD

**Issue by nicostuhlfauth** [michaelfitzhavey/vue-json-tree-view#29]
Please add typings `@types/vue-json-tree-view`, so Typescript works out-of-the-box.

**Comment by michaelfitzhavey** [comment]
Hi @nicostuhlfauth, I'm not all that familiar with adding typings myself. If anyone would like to submit a pull request it would be very welcome!

**Comment by nicostuhlfauth** [comment]
@michaelfitzhavey Typically, typings for JS projects will not be added directly into the package, but instead they will be published seperately at `@types/<npm project name>`. There is a generator that worked pretty well for the project I am working on. Simply generate the typings and open a PR, as described here: https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

**Comment by michaelfitzhavey** [comment]
Publishing is currently [blocked](https://github.com/michaelfitzhavey/vue-json-tree-view/issues/25#issuecomment-416640248) but I'll look into this. Thanks!

**Comment by tylerkrupicka** [comment]
I created a package similar to this one https://github.com/tylerkrupicka/vue-json-component which is written in TypeScript and exports types with the package. If it works for your use-case go ahead and try it out.

**Comment by nicostuhlfauth** [comment]
@tylerkrupicka Thanks for your response and creating a package. However, we decided to switch to React. But I'll keep it in mind for future projects.

**Comment by michaelfitzhavey** [comment]
Should be fixed now this is merged: https://github.com/michaelfitzhavey/vue-json-tree-view/pull/32
