### ISSUE TITLE
JSFiddle Example does not work 

### ISSUE THREAD

**Issue by Dzenly** [michaelfitzhavey/vue-json-tree-view#33]
https://jsfiddle.net/arvidkahl/kwo6vk9d/11/

After "Run" button pressing there is such error:

```
Uncaught ReferenceError: Vue is not defined
    at <anonymous>:3:1
    at run (babel.js:60802)
    at check (babel.js:60868)
    at loadScripts (babel.js:60909)
    at runScripts (babel.js:60936)
    at transformScriptTags (babel.js:324)
```

**Comment by michaelfitzhavey** [comment]
This is not the behaviour being seen by myself or some others I'm sending this link to. Closing this issue for now.

If you are still seeing this do re open another issue, I suspect it was a temporary problem with JSFiddle.
