### ISSUE TITLE
json can't parse

### ISSUE THREAD

**Issue by XerneaX** [michaelfitzhavey/vue-json-tree-view#34]
`
sampleData: ["{\"timestamp\":\"2019-02-12T10:20:32.550+0300\",\"record\":{\"position\":-1,\"header\":{\"digest\":null,\"version\":null,\"contentLength\":292,\"date\":\"2013-05-18T08:38:55Z\",\"headerFields\":{\"reader-identifier\":\"crawl-data/CC-MAIN-2013-20/segments/1368696381630/warc/CC-MAIN-20130516092621-00000-ip-10-60-113-184.ec2.internal.warc.gz\",\"WARC-IP-Address\":\"184.154.38.27\",\"absolute-offset\":152576079,\"WARC-Target-URI\":\"http://mocanomi.org/product/roberto-juarez-a-sense-of-place/?add-to-cart=4734&_n=87beaddeca\",\"WARC-Warcinfo-ID\":\"<urn:uuid:b736a179-817d-4f61-b1de-58c80ec9d549>\",\"WARC-Date\":\"2013-05-18T08:38:55Z\",\"Content-Length\":\"292\",\"WARC-Record-ID\":\"<urn:uuid:a27442d4-32ea-42f4-a8fb-56d1634056c5>\",\"WARC-Type\":\"request\",\"Content-Type\":\"application/http; msgtype=request\"},\"mimetype\":\"application/http; msgtype=request\",\"contentBegin\":-1,\"recordIdentifier\":null,\"url\":\"http://mocanomi.org/product/roberto-juarez-a-sense-of-place/?add-to-cart=4734&_n=87beaddeca\",\"headerFieldKeys\":[\"reader-identifier\",\"WARC-IP-Address\",\"absolute-offset\",\"WARC-Target-URI\",\"WARC-Warcinfo-ID\",\"WARC-Date\",\"Content-Length\",\"WARC-Record-ID\",\"WARC-Type\",\"Content-Type\"],\"readerIdentifier\":\"crawl-data/CC-MAIN-2013-20/segments/1368696381630/warc/CC-MAIN-20130516092621-00000-ip-10-60-113-184.ec2.internal.warc.gz\",\"length\":291,\"offset\":152576079},\"digestStr\":null,\"strict\":false},\"project\":\"cn-warc\",\"type\":\"warc\"}"],
`
![jsontreebug](https://user-images.githubusercontent.com/17777513/52632667-309bba00-2ed3-11e9-933e-461f2cfe2270.png)

js fiddle link 
[https://jsfiddle.net/aoLbpwr8/](url)

**Comment by xerCess** [comment]
if we use in json length with a  number like length: 12 this package doesnt work @michaelfitzhavey

**Comment by ericmdantas** [comment]
Yep, just got bit by this too.

If you have an object that has a property `length`, then that object is parsed as an array instead of an object.

Here's an example ([check it on jsfiddle](https://jsfiddle.net/dhzp47Lg/)):

```js
Vue.use(TreeView);  
new Vue({
  el: '#app',
  data: {
    jsonSource: {
      myObject: {
        b: 1,
        c: 2,
      },
      myOtherObject: {
        d: 4,
        e: 5,
      },
      thisShouldBeAnObjectToo: {
        f: 6,
        g: 7,
        length: 999 // <-- this makes the object to be parsed as an Array
      },
      thisIsAnArray: [
      	{h: 8, i: 9},
        {h: 88, i: 99},
        {h: 888, i: 999},
      ]
    }
  }
})
```

**Comment by fitzhavey** [comment]
Thanks both for the examples, I'll take a look into this

**Comment by ericmdantas** [comment]
This is still a known issue. Can you reopen @michaelfitzhavey?
