### ISSUE TITLE
Domain digimondo.io doesn't exist 

### ISSUE THREAD

**Issue by duduindo** [michaelfitzhavey/vue-json-tree-view#37]
URL: https://devblog.digimondo.io/building-a-json-tree-view-component-in-vue-js-from-scratch-in-six-steps-ce0c05c2fdd8#.dkwh4jo2m

**Comment by arvidkahl** [comment]
The company closed their dev blog. I have left there a few years ago. It was a medium-hosted blog post, and people shamelessly copied it without attribution, so if someone would like to re-host it somewhere safe (preferrably with proper attribution), that would be awesome:

- http://brianyang.com/building-a-json-tree-view-component-in-vue-js-from-scratch-in-six-steps/

(Never would I have thought that I'd be slightly thankful for someone stealing my content)

**Comment by michaelfitzhavey** [comment]
I also stumbled upon this link and happened to have updated it in the readme. This should be fixed, temporarily at least.
