### ISSUE TITLE
Would anyone like to manage this repo?

### ISSUE THREAD

**Issue by michaelfitzhavey** [michaelfitzhavey/vue-json-tree-view#38]
There have been some great change requests and a couple fantastic PRs. Unfortunately I've found myself too busy to manage releases in a reasonable timeframe - if anyone else would like to take over from me please comment below.

**Comment by telmaantunes** [comment]
I can help manage

**Comment by WajuAbolarin** [comment]
I would like to help

**Comment by Chrisimir** [comment]
Would love to help

**Comment by michaelfitzhavey** [comment]
Thanks both, I have invited you as collaborators:

![image](https://user-images.githubusercontent.com/2746248/74610636-c670b300-50ec-11ea-9795-324bd6e13343.png)

I'm happy to help out where I can also. I've been stretched across work and many other projects lately, myself + all users of this package really appreciate your support.
