### ISSUE TITLE
Shorten large values

### ISSUE THREAD

**Issue by simontong** [michaelfitzhavey/vue-json-tree-view#7]
Hi,

Is it possible to make it so that long values can be shortened with an ellipsis that, when clicked, will expand the value?

Thanks

**Comment by yangxikun** [comment]
try custom the style:
```
<style lang="stylus">
  .tree-view-item-value-string
    white-space: normal
</style>
```

**Comment by michaelfitzhavey** [comment]
Combining `text-overflow: ellipsis` with @yangxikun 's solution does the trick
