### ISSUE TITLE
Select Node Event

### ISSUE THREAD

**Issue by winterbest** [michaelfitzhavey/vue-json-tree-view#8]
Hi, is there any way to get the node data which I clicked ?
I used $emit method but it not work.

**Comment by arvidkahl** [comment]
Where did you emit that event? Can you show some code?

I would add a `@click="handleClick"` attribute to the `class="tree-view-item-leaf` div. The method itself would then need a Vue instance to $emit the event on. I wrote a blogpost about Event Buses in vue at https://devblog.digimondo.io/building-a-simple-eventbus-in-vue-js-64b70fb90834#.oc8r04by9 . Maybe use that.

**Comment by wintergithub** [comment]
Sry, I forgot the code link:  [https://jsfiddle.net/kwo6vk9d/33/](https://jsfiddle.net/kwo6vk9d/33/).
First, I added send method & @click="send(data) attribute in tree-view-item component. Then, I added get method & @get-node="get" in tree-view component.

Thanks for your replay, I'll try event bus later.

**Comment by arvidkahl** [comment]
Really quick solution to play around with:https://jsfiddle.net/7trz0jsn/2/

The trick is to reference the `$root` property of the this context and emit and listen to events there - like a very cheap event bus. Also, you need to register the listener in the tree view component. For some reason, the event fires twice, but i'll leave that to you :)

**Comment by arvidkahl** [comment]
You could probably make a very cool event system with that. All opened / closed / clicked events could be done with this. now what you could also build here is what is talked about in #1 - programmatic opening/closing :) If you get around to that, i would certainly merge that pull request ;)

**Comment by wintergithub** [comment]
It worked. Thank u so much! I also tried the bus event method, it worked very well too.
I think it's a very useful thing to add the feature. :)
